# Generated by Django 6.0.6 on 2026-07-22 01:12

import django.core.validators
import django.db.models.deletion
import pedido.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido (7-15 dígitos).', regex='^\\+?1?\\d{7,15}$')], verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tracking', models.CharField(default=pedido.models.generar_tracking, editable=False, max_length=20, unique=True, verbose_name='Número de tracking')),
                ('tipo_servicio', models.CharField(choices=[('aereo', 'Aéreo'), ('maritimo', 'Marítimo'), ('terrestre', 'Terrestre'), ('tren', 'Tren')], max_length=20, verbose_name='Tipo de servicio')),
                ('origen', models.CharField(max_length=200, verbose_name='Origen')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('descripcion_carga', models.TextField(verbose_name='Descripción de la carga')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Peso (kg)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='pedido.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
