# Generated by Django 6.0.7 on 2026-07-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('provincia', models.CharField(blank=True, max_length=100)),
                ('tarifa_base', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tarifa Base ($)')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(db_index=True, editable=False, max_length=25, unique=True, verbose_name='Número de Guía')),
                ('nombre_destinatario', models.CharField(max_length=150, verbose_name='Nombre Destinatario')),
                ('telefono_destinatario', models.CharField(max_length=15, verbose_name='Teléfono Destinatario')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('descripcion_paquete', models.TextField(verbose_name='Descripción del Paquete')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Peso (kg)')),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Declarado ($)')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo de Envío ($)')),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('RECIBIDA', 'Recibida'), ('EN_CLASIFICACION', 'En Clasificación'), ('EN_DESPACHO', 'En Despacho'), ('EN_TRANSITO', 'En Tránsito'), ('LLEGO_A_DESTINO', 'Llegó a Destino'), ('EN_ENTREGA', 'En Entrega'), ('ENTREGADA', 'Entregada'), ('NO_ENTREGADA', 'No Entregada')], default='REGISTRADA', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ciudad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='pedido.ciudad', verbose_name='Ciudad Destino')),
                ('secretario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Encomienda',
                'verbose_name_plural': 'Encomiendas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('RECIBIDA', 'Recibida'), ('EN_CLASIFICACION', 'En Clasificación'), ('EN_DESPACHO', 'En Despacho'), ('EN_TRANSITO', 'En Tránsito'), ('LLEGO_A_DESTINO', 'Llegó a Destino'), ('EN_ENTREGA', 'En Entrega'), ('ENTREGADA', 'Entregada'), ('NO_ENTREGADA', 'No Entregada')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedido.encomienda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado',
                'verbose_name_plural': 'Historial de Estados',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CLIENTE', 'Cliente'), ('SECRETARIO', 'Secretario'), ('DESPACHADOR', 'Despachador')], default='CLIENTE', max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('cedula', models.CharField(blank=True, max_length=13, verbose_name='Cédula')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.AddField(
            model_name='encomienda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='pedido.perfilusuario', verbose_name='Cliente (Remitente)'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='despachador_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encomiendas_asignadas', to='pedido.perfilusuario', verbose_name='Despachador Asignado'),
        ),
    ]
