# Generated by Django 6.0.6 on 2026-07-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='destinatario',
            field=models.CharField(default='Desconocido', max_length=100, verbose_name='Nombre del destinatario'),
        ),
    ]
