# Generated by Django 6.0.5 on 2026-07-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='foto_producto',
            field=models.FileField(blank=True, null=True, upload_to='productos/', verbose_name='Foto del producto'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo en oficina'), ('transferencia', 'Transferencia bancaria'), ('tarjeta', 'Tarjeta de crédito/débito')], max_length=20, null=True, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pago_confirmado',
            field=models.BooleanField(default=False, verbose_name='Pago confirmado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio de envío ($)'),
        ),
    ]
