# Generated by Django 6.0.7 on 2026-07-22 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_comprobante_pago_pedido_foto_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='despachador',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Despachador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Despachador asignado'),
        ),
    ]
