# Generated by Django 6.0.6 on 2026-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_despachador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='destinatario',
            field=models.CharField(max_length=100, verbose_name='Nombre del destinatario'),
        ),
    ]
